dataset:
    - Simbayes:
        seed: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
        n_samples: [1000000]
        noise: [1]
solver:
    - ExtraTrees
    - RandomForest
    - HistGradientBoosting
    - SVM
    - XGBoost